apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-serving
  annotations:
    scenarios.ai.sap.com/name: "Hello World Serving"
    scenarios.ai.sap.com/description: "Simple serving executable to return a greeting"
    executables.ai.sap.com/name: "Hello World Server"
    executables.ai.sap.com/description: "Returns a static greeting via a simple server"
  labels:
    scenarios.ai.sap.com/id: "hello-world-example"
    ai.sap.com/version: "2.0"
spec:
  imagePullSecrets:
    - name: credstutorialrepo
  entrypoint: serve-greeting
  templates:
    - name: serve-greeting
      container:
        image: shirke0706/helloworldcode:01
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo -e "HTTP/1.1 200 OK\nContent-Type: text/plain\n\nHello from the Serving Executable!" | nc -l -p 8080
      ports:
        - containerPort: 8080
